name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            arch: linux-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            arch: linux-intel
          - target: aarch64-apple-darwin
            os: macos-latest
            arch: apple-arm
          - target: x86_64-apple-darwin
            os: macos-latest
            arch: apple-intel
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: week
          target: ${{ matrix.arch }}
          token: ${{ secrets.GITHUB_TOKEN }}
